application: hw8
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /(.*\.html)$
  static_files: \1
  upload: (.*\.html)$
    
- url: /(.*\.(gif|png|jpg|js|css|json))$
  static_files: \1
  upload: .*\.(gif|png|jpg|js|css|json)$
  
- url: /(.+\.php)$
  script: \1
